# This is a basic workflow to help you get started with Actions

name: Deploy to S3

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install Brew
        run: mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
      - name: Install Hugo
        run: |
          brew install hugo --force --quiet
          git submodule init
          git submodule update
      - name: Build Hugo Site
        run: |
          cd landing_page
          hugo
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hugo_build
          path: ./landing_page/public
          retention-days: 1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "ap-southeast-2"
      AWS_S3_BUCKET: "s3://hereocity-build/"
      AWS_CLOUDFRONT_DISTRIBUTION_ID: "E1GBA8OUP7ARWJ"
      AWS_CLOUDFRONT_DISTRIBUTION_INVALIDATION_PATH: "/*"
      LOCAL_HUGO_PUBLIC_PATH: "./landing_page/public/"
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: hugo_build
          path: ./landing_page/public
      - run: |
          aws s3 rm $AWS_S3_BUCKET --recursive
          aws s3 cp $LOCAL_HUGO_PUBLIC_PATH $AWS_S3_BUCKET --recursive
          aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths $AWS_CLOUDFRONT_DISTRIBUTION_INVALIDATION_PATH