# This is a basic workflow to help you get started with Actions

name: Deploy to S3

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Install Brew
      - uses: actions/checkout@v3
        run: |
          mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
          eval "$(homebrew/bin/brew shellenv)"
          brew update --force --quiet
          chmod -R go-w "$(brew --prefix)/share/zsh"
      # Runs a single command using the runners shell
      - name: Install Hugo
        run: brew install hugo --force --quiet
      # Runs a set of commands using the runners shell
      - name: Build Hugo Site
        run: |
          cd landing_page
          hugo -D
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "ap-southeast-2"
      AWS_S3_BUCKET: "s3://hereocity-build/"
      AWS_CLOUDFRONT_DISTRIBUTION_ID: "E1GBA8OUP7ARWJ"
      AWS_CLOUDFRONT_DISTRIBUTION_INVALIDATION_PATH: "/*"
      LOCAL_HUGO_PUBLIC_PATH: "./landing_page/public/"
    steps:
      - uses: actions/checkout@v3
      - run: |
          aws s3 rm $AWS_S3_BUCKET --recursive
          aws s3 cp $LOCAL_HUGO_PUBLIC_PATH $AWS_S3_BUCKET --recursive
          aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths $AWS_CLOUDFRONT_DISTRIBUTION_INVALIDATION_PATH